### PR TITLE
styles: fix onboarding success page design

### LINKED ISSUE #411: Match the design of the profile creation success page to the figma link
The design as of now looks very out of place: 
image

Match the design of those two cards with the one in the following figma link: https://www.figma.com/file/32RTTrXJb8MQo8bz833ioA?embed_host=oembed&kind=file&node-id=2033-860&type=design&viewer=1

## Steps to Reproduce the Problem

1. Create a talent profile
2. Get to the success page

### PR DESCRIPTION
**Pull request by SkTomsi**
## What does this PR do?
fixes the profile creation success page ui so that it matches the figma mockup
## Where should the reviewer start?
create a new profile or can view previously submitted bounty page to see the talentBio component 

## Screenshots (if appropriate)
before:
image

after:
image

### CODE REVIEW

File: src/pages/new/talent.tsx [hunk 1]
```diff
@@ -12,6 +13,7 @@ import {
 import type { User } from '@prisma/client';
 import axios from 'axios';
 import { type GetServerSideProps } from 'next';
+import { getURL } from 'next/dist/shared/lib/utils';
```
Comment (a20hek) [inline src/pages/new/talent.tsx:16]: wrong import; please fix this

File: src/pages/new/talent.tsx [hunk 2]
```diff
@@ -25,7 +27,6 @@ import { TalentBio } from '@/components/TalentBio';
 import { Default } from '@/layouts/Default';
 import { Meta } from '@/layouts/Meta';
 import { userStore } from '@/store/user';
-import { getURL } from '@/utils/validUrl';
```
Comment (a20hek) [inline src/pages/new/talent.tsx:28]: here's the right import

**Review by a20hek — CHANGES_REQUESTED** [review]

**Review by a20hek — APPROVED** [review]
lgtm
