### PR TITLE
styles: detailed submission page fixes

### LINKED ISSUE #622: Overflow:X Ui Bug in mobile view for Winner of project
## Expected Behavior
it should fit properly in mobile view , the bar should not be that wide in mobile view same for winner profile should be center and no overflow
lastly grants submit button , should be bit above

## Actual Behavior

<div style="display: flex; flex-wrap: nowrap;">
    earnbug2
    earnbug
    earn
</div>

## Steps to Reproduce the Problem

1. Check any Project or bounty which have any winner announced in mobile view
2. Check any grant in mobile view

### PR DESCRIPTION
**Pull request by rahulsingh2312**
## What does this PR do?
I edited the Listing Submission page to fix the current Ui bug of Overflowing components, and The submission button in Grants page 

## Where should the reviewer start?
src/features/listings/components/SubmissionsPage/SubmissionPage.tsx
src/pages/grants/[id].tsx

## How should this be manually tested?
Look at the current listing in which someone have already won the bounty/project and then the vercel deployment of this PR

## Any background context you want to provide?
Ui bugs in submission page and grant page
## What are the relevant issues?
fixes #622 
## After this PR : 

<div style="display: flex; flex-wrap: nowrap;">
    earnbug2
    earnbug2
    earn
</div>
 earnbug

### Before this PR:

<div style="display: flex; flex-wrap: nowrap;">
    earnbug2
    earnbug
    earn
</div>

### CODE REVIEW

File: src/pages/grants/[id].tsx [hunk 1]
```diff
@@ -130,7 +130,7 @@ const Grants = ({ slug }: GrantsDetailsProps) => {
                   <Flex
                     pos={{ base: 'fixed', md: 'static' }}
                     zIndex={999}
-                    bottom={0}
+                    bottom={12}
```
Comment (a20hek) [inline src/pages/grants/[id].tsx:133]: this is a change from an earlier commit; should have checked out from staging again for the new PR

Comment (rahulsingh2312) [reply src/pages/grants/[id].tsx:133]: hey abhishek actually no , The grants page is seperate , in the previous PR i just fixed the Grants and Projects page . as you can see i have pointed this in the issue aswell .

Comment (a20hek) [reply src/pages/grants/[id].tsx:133]: ahh understood
my bad

**Review by a20hek — APPROVED** [review]
