### PR TITLE
styles: sponsor landing page fixes

### LINKED ISSUE #573: Fix: Sponsor Page UI
## Expected Behavior
image
image
image

## Actual Behavior
- FAQs animation on collapse has a weird delay
- Listing Work is overflowing, it rather be scrollable
- Stats are not centered from tablet and below

### PR DESCRIPTION
**Pull request by Manice18**
## What does this PR do?
closes #573 

## Screenshots (if appropriate)

### CODE REVIEW

File: src/features/sponsor/components/FAQs.tsx [hunk 1]
```diff
@@ -65,12 +65,17 @@ export function FAQs() {
...
           <AccordionItem
             key={faq.question}
+            my="1rem"
             bg="white"
             border="0"
             rounded="0.25rem"
           >
             <h2>
-              <AccordionButton my="1rem" py="0.8rem" rounded="0.25rem">
+              <AccordionButton
```
Comment (a20hek) [inline src/features/sponsor/components/FAQs.tsx:74]: need a transition while opening too; currently transition shows up only when closing the accordion

File: src/features/sponsor/components/ListingWork.tsx [hunk 2]
```diff
@@ -90,7 +90,13 @@ export function ListingWork() {
...
           Get almost any kind of work done
         </Text>
-        <HStack pos="relative" align="start" gap={8} maxW={maxW}>
+        <HStack
+          pos="relative"
+          align="start"
+          gap={8}
+          overflow={'scroll'}
+          maxW={{ base: '100%' }}
+        >
```
Comment (a20hek) [inline src/features/sponsor/components/ListingWork.tsx:99]: image

show a little bit of the 4th testimonial so that someone knows its scrollable – or maybe let the container for testimonials get bigger than the container of the page to fit a bit of the 4th testimonial

**Review by a20hek — CHANGES_REQUESTED** [review]

File: src/features/sponsor/components/FAQs.tsx (hunk 1 above)
Comment (Manice18) [reply src/features/sponsor/components/FAQs.tsx:74]: The opening transition is not working at all, I tried it for long.
I also tried pasting an example component code from Chakraui's accordion, but the issue persisted there too.

Comment (a20hek) [reply src/features/sponsor/components/FAQs.tsx:74]: try passing props

File: src/features/sponsor/components/ListingWork.tsx (hunk 2 above)
Comment (Manice18) [reply src/features/sponsor/components/ListingWork.tsx:99]: image
is this fine?

File: src/features/sponsor/components/FAQs.tsx (hunk 1 above)
Comment (Manice18) [reply src/features/sponsor/components/FAQs.tsx:74]: tried all possibilities.

Comment (Manice18) [reply src/features/sponsor/components/FAQs.tsx:74]: Just saw that it's an issue in Chakra UI itself:
https://github.com/chakra-ui/chakra-ui/issues/8448

**Review by a20hek — APPROVED** [review]

File: src/features/sponsor/components/ListingWork.tsx (hunk 2 above)
Comment (a20hek) [reply src/features/sponsor/components/ListingWork.tsx:99]: but on larger screens, it looks weird
why dont you add an infinite horizontal scroll for them

Comment (a20hek) [reply src/features/sponsor/components/ListingWork.tsx:99]: it should keep scrolling on its own

Comment (Manice18) [reply src/features/sponsor/components/ListingWork.tsx:99]: ya got it.

**Comment by Manice18** [comment]
@a20hek can you check now?

**Review by a20hek — APPROVED** [review]
